### ISSUE TITLE
An error has occurred: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by LeninZapata** [jordon31/OnlySnap#42]
After updating the requirements, I run the file but I get these errors, what could it be?
https://i.imgur.com/WfI4IpR.png
![image](https://github.com/jordon31/OnlySnap/assets/42600954/2e78ba9f-6011-446b-874f-0198b507c0d8)

**Comment by jordon31** [comment]
fixed with next update.. pls wait

**Comment by jordon31** [comment]
updated @LeninZapata

**Comment by LeninZapata** [comment]
Now if it downloads!, I download half and then I had network problems and I don't download the other half, I guess it's an IP problem.

**Comment by LeninZapata** [comment]
I thought it was my Network, but right now you can see the photos on the page and I executed the download but unfortunately it does not download all the videos and photos, it shows them as an error image. What could it be?

user test: abigaiilmorrisfree

![image](https://github.com/jordon31/OnlySnap/assets/42600954/847bc073-17bf-4ef8-a474-30bf3f741f3f)
![image](https://github.com/jordon31/OnlySnap/assets/42600954/281b2c4b-dde3-4981-8c24-17a6c8493e9c)

**Comment by jordon31** [comment]
no error log? and i see multiple photos.. i need test manual for check.. thanks

**Comment by jordon31** [comment]
I have now done it.. I did not have any problems.. I think it was due to when you had network problems it caused issues.. delete the cache of the profile and reload everything if you find missing posts and because there is the blocking of ADV you can disable on the config file "link" from false to true.. for the profile cache if you do not know the profile id go to the dump folder and find "id" and from there you know.. go to the cache folder and delete the profile's cache folder..
